image: node:18

stages:
  - install
  - build
  - deploy

variables:
  VITE_CONVEX_URL: ${CONVEX_URL}
  VITE_CLERK_PUBLISHABLE_KEY: ${CLERK_PUBLISHABLE_KEY}

# Modificamos el caché para incluir los workspaces
cache:
  paths:
    - node_modules/
    - ../../node_modules/
    - ../../packages/*/node_modules/

install_dependencies:
  stage: install
  script:
    - cd ../../ # Volvemos a la raíz del monorepo
    - npm install
    - cd apps/web # Volvemos al proyecto web
    - npm install

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  needs:
    - install_dependencies

deploy_staging:
  stage: deploy
  script:
    - npm install -g vercel
    - vercel --token ${VERCEL_TOKEN} --confirm
  environment:
    name: staging
  only:
    - develop
  needs:
    - build

deploy_production:
  stage: deploy
  script:
    - npm install -g vercel
    - vercel --prod --token ${VERCEL_TOKEN} --confirm
  environment:
    name: production
  only:
    - main
  when: manual
  needs:
    - build
