/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminLoginRouteImport } from './routes/super-admin/login'
import { Route as SuperAdminForgotPasswordRouteImport } from './routes/super-admin/forgot-password'
import { Route as SuperAdminDashboardRouteImport } from './routes/super-admin/dashboard'
import { Route as SuperAdminTrainersIndexRouteImport } from './routes/super-admin/trainers/index'
import { Route as SuperAdminSedesIndexRouteImport } from './routes/super-admin/sedes/index'
import { Route as SuperAdminPersonalIndexRouteImport } from './routes/super-admin/personal/index'
import { Route as SuperAdminTrainersNewRouteImport } from './routes/super-admin/trainers/new'
import { Route as SuperAdminTrainersEditRouteImport } from './routes/super-admin/trainers/edit'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminLoginRoute = SuperAdminLoginRouteImport.update({
  id: '/super-admin/login',
  path: '/super-admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminForgotPasswordRoute =
  SuperAdminForgotPasswordRouteImport.update({
    id: '/super-admin/forgot-password',
    path: '/super-admin/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperAdminDashboardRoute = SuperAdminDashboardRouteImport.update({
  id: '/super-admin/dashboard',
  path: '/super-admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminTrainersIndexRoute = SuperAdminTrainersIndexRouteImport.update({
  id: '/super-admin/trainers/',
  path: '/super-admin/trainers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminSedesIndexRoute = SuperAdminSedesIndexRouteImport.update({
  id: '/super-admin/sedes/',
  path: '/super-admin/sedes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminPersonalIndexRoute = SuperAdminPersonalIndexRouteImport.update({
  id: '/super-admin/personal/',
  path: '/super-admin/personal/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminTrainersNewRoute = SuperAdminTrainersNewRouteImport.update({
  id: '/super-admin/trainers/new',
  path: '/super-admin/trainers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminTrainersEditRoute = SuperAdminTrainersEditRouteImport.update({
  id: '/super-admin/trainers/edit',
  path: '/super-admin/trainers/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/forgot-password': typeof SuperAdminForgotPasswordRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/super-admin/trainers/edit': typeof SuperAdminTrainersEditRoute
  '/super-admin/trainers/new': typeof SuperAdminTrainersNewRoute
  '/super-admin/personal': typeof SuperAdminPersonalIndexRoute
  '/super-admin/sedes': typeof SuperAdminSedesIndexRoute
  '/super-admin/trainers': typeof SuperAdminTrainersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/forgot-password': typeof SuperAdminForgotPasswordRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/super-admin/trainers/edit': typeof SuperAdminTrainersEditRoute
  '/super-admin/trainers/new': typeof SuperAdminTrainersNewRoute
  '/super-admin/personal': typeof SuperAdminPersonalIndexRoute
  '/super-admin/sedes': typeof SuperAdminSedesIndexRoute
  '/super-admin/trainers': typeof SuperAdminTrainersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/forgot-password': typeof SuperAdminForgotPasswordRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/super-admin/trainers/edit': typeof SuperAdminTrainersEditRoute
  '/super-admin/trainers/new': typeof SuperAdminTrainersNewRoute
  '/super-admin/personal/': typeof SuperAdminPersonalIndexRoute
  '/super-admin/sedes/': typeof SuperAdminSedesIndexRoute
  '/super-admin/trainers/': typeof SuperAdminTrainersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/super-admin/dashboard'
    | '/super-admin/forgot-password'
    | '/super-admin/login'
    | '/super-admin/trainers/edit'
    | '/super-admin/trainers/new'
    | '/super-admin/personal'
    | '/super-admin/sedes'
    | '/super-admin/trainers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/super-admin/dashboard'
    | '/super-admin/forgot-password'
    | '/super-admin/login'
    | '/super-admin/trainers/edit'
    | '/super-admin/trainers/new'
    | '/super-admin/personal'
    | '/super-admin/sedes'
    | '/super-admin/trainers'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/super-admin/dashboard'
    | '/super-admin/forgot-password'
    | '/super-admin/login'
    | '/super-admin/trainers/edit'
    | '/super-admin/trainers/new'
    | '/super-admin/personal/'
    | '/super-admin/sedes/'
    | '/super-admin/trainers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SuperAdminDashboardRoute: typeof SuperAdminDashboardRoute
  SuperAdminForgotPasswordRoute: typeof SuperAdminForgotPasswordRoute
  SuperAdminLoginRoute: typeof SuperAdminLoginRoute
  SuperAdminTrainersEditRoute: typeof SuperAdminTrainersEditRoute
  SuperAdminTrainersNewRoute: typeof SuperAdminTrainersNewRoute
  SuperAdminPersonalIndexRoute: typeof SuperAdminPersonalIndexRoute
  SuperAdminSedesIndexRoute: typeof SuperAdminSedesIndexRoute
  SuperAdminTrainersIndexRoute: typeof SuperAdminTrainersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/login': {
      id: '/super-admin/login'
      path: '/super-admin/login'
      fullPath: '/super-admin/login'
      preLoaderRoute: typeof SuperAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/forgot-password': {
      id: '/super-admin/forgot-password'
      path: '/super-admin/forgot-password'
      fullPath: '/super-admin/forgot-password'
      preLoaderRoute: typeof SuperAdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/dashboard': {
      id: '/super-admin/dashboard'
      path: '/super-admin/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof SuperAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/trainers/': {
      id: '/super-admin/trainers/'
      path: '/super-admin/trainers'
      fullPath: '/super-admin/trainers'
      preLoaderRoute: typeof SuperAdminTrainersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/sedes/': {
      id: '/super-admin/sedes/'
      path: '/super-admin/sedes'
      fullPath: '/super-admin/sedes'
      preLoaderRoute: typeof SuperAdminSedesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/personal/': {
      id: '/super-admin/personal/'
      path: '/super-admin/personal'
      fullPath: '/super-admin/personal'
      preLoaderRoute: typeof SuperAdminPersonalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/trainers/new': {
      id: '/super-admin/trainers/new'
      path: '/super-admin/trainers/new'
      fullPath: '/super-admin/trainers/new'
      preLoaderRoute: typeof SuperAdminTrainersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/trainers/edit': {
      id: '/super-admin/trainers/edit'
      path: '/super-admin/trainers/edit'
      fullPath: '/super-admin/trainers/edit'
      preLoaderRoute: typeof SuperAdminTrainersEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SuperAdminDashboardRoute: SuperAdminDashboardRoute,
  SuperAdminForgotPasswordRoute: SuperAdminForgotPasswordRoute,
  SuperAdminLoginRoute: SuperAdminLoginRoute,
  SuperAdminTrainersEditRoute: SuperAdminTrainersEditRoute,
  SuperAdminTrainersNewRoute: SuperAdminTrainersNewRoute,
  SuperAdminPersonalIndexRoute: SuperAdminPersonalIndexRoute,
  SuperAdminSedesIndexRoute: SuperAdminSedesIndexRoute,
  SuperAdminTrainersIndexRoute: SuperAdminTrainersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
