/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminTrainersIndexRouteImport } from './routes/admin/trainers/index'
import { Route as AdminSedesIndexRouteImport } from './routes/admin/sedes/index'
import { Route as AdminPersonalIndexRouteImport } from './routes/admin/personal/index'
import { Route as AdminTrainersNewRouteImport } from './routes/admin/trainers/new'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrainersIndexRoute = AdminTrainersIndexRouteImport.update({
  id: '/admin/trainers/',
  path: '/admin/trainers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSedesIndexRoute = AdminSedesIndexRouteImport.update({
  id: '/admin/sedes/',
  path: '/admin/sedes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPersonalIndexRoute = AdminPersonalIndexRouteImport.update({
  id: '/admin/personal/',
  path: '/admin/personal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrainersNewRoute = AdminTrainersNewRouteImport.update({
  id: '/admin/trainers/new',
  path: '/admin/trainers/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/todos': typeof TodosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/trainers/new': typeof AdminTrainersNewRoute
  '/admin/personal': typeof AdminPersonalIndexRoute
  '/admin/sedes': typeof AdminSedesIndexRoute
  '/admin/trainers': typeof AdminTrainersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/todos': typeof TodosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/trainers/new': typeof AdminTrainersNewRoute
  '/admin/personal': typeof AdminPersonalIndexRoute
  '/admin/sedes': typeof AdminSedesIndexRoute
  '/admin/trainers': typeof AdminTrainersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/todos': typeof TodosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/trainers/new': typeof AdminTrainersNewRoute
  '/admin/personal/': typeof AdminPersonalIndexRoute
  '/admin/sedes/': typeof AdminSedesIndexRoute
  '/admin/trainers/': typeof AdminTrainersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/todos'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/trainers/new'
    | '/admin/personal'
    | '/admin/sedes'
    | '/admin/trainers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/todos'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/trainers/new'
    | '/admin/personal'
    | '/admin/sedes'
    | '/admin/trainers'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/todos'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/trainers/new'
    | '/admin/personal/'
    | '/admin/sedes/'
    | '/admin/trainers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  TodosRoute: typeof TodosRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminTrainersNewRoute: typeof AdminTrainersNewRoute
  AdminPersonalIndexRoute: typeof AdminPersonalIndexRoute
  AdminSedesIndexRoute: typeof AdminSedesIndexRoute
  AdminTrainersIndexRoute: typeof AdminTrainersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trainers/': {
      id: '/admin/trainers/'
      path: '/admin/trainers'
      fullPath: '/admin/trainers'
      preLoaderRoute: typeof AdminTrainersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sedes/': {
      id: '/admin/sedes/'
      path: '/admin/sedes'
      fullPath: '/admin/sedes'
      preLoaderRoute: typeof AdminSedesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/personal/': {
      id: '/admin/personal/'
      path: '/admin/personal'
      fullPath: '/admin/personal'
      preLoaderRoute: typeof AdminPersonalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trainers/new': {
      id: '/admin/trainers/new'
      path: '/admin/trainers/new'
      fullPath: '/admin/trainers/new'
      preLoaderRoute: typeof AdminTrainersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  TodosRoute: TodosRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminTrainersNewRoute: AdminTrainersNewRoute,
  AdminPersonalIndexRoute: AdminPersonalIndexRoute,
  AdminSedesIndexRoute: AdminSedesIndexRoute,
  AdminTrainersIndexRoute: AdminTrainersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
